spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000    #설정한 size만큼 쿼리를 조회한다.

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace